export const TYPES = {
  HOME: "HOME",
  HOME_SUCCESS: "HOME_SUCCESS",
  HOME_ERROR: "HOME_ERROR",

  MENU: "MENU",
  MENU_SUCCESS: "MENU_SUCCESS",
  MENU_ERROR: "MENU_ERROR",

  ERROR: "ERROR",
  ERROR_CLEAR: "ERROR_CLEAR",
};
