export const TYPES = {
  HOME: "HOME",
  HOME_SUCCESS: "HOME_SUCCESS",
  HOME_ERROR: "HOME_ERROR",

  MENU: "MENU",
  MENU_SUCCESS: "MENU_SUCCESS",
  MENU_ERROR: "MENU_ERROR",

  ERROR: "ERROR",
  ERROR_CLEAR: "ERROR_CLEAR",

  SECTION: "SECTION",
  SECTION_SUCCESS: "SECTION_SUCCESS",
  SECTION_ERROR: "SECTION_ERROR",

  CHANNEL: "CHANNEL",
  CHANNEL_SUCCESS: "CHANNEL_SUCCESS",
  CHANNEL_ERROR: "CHANNEL_ERROR",

  CATCHUP: "CATCHUP",
  CATCHUP_SUCCESS: "CATCHUP_SUCCESS",
  CATCHUP_ERROR: "CATCHUP_ERROR",
};
